- name: install nginx and run nginx
  hosts: webservers
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
      name: nginx
      state: present
   - name: run the nginx
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
   - name: print something
     ansible.builtin.debug:
      msg: I am learning devops with aws   