- name: print message and install and run nginx
  host: webservers
  become: yes
  tasks:
   - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
   - name: start nginx server
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes