- name: print message and install and run nginx
  hosts: webservers
  become: true
  tasks:
   - name: print message
     ansible.builtin.debug:
       msg: Hello Indu I LOVE YOU....
   - name: install nginx
     ansible.builtin.package:
       name: nginx
       state: latest
   - name: run nginx
     ansible.builtin.service:
       name: nginx
       state: started