- name: install nginx server
  hosts: webservers
  become: true
  tasks:
   - name: install nginx
     ansible.builtin.debug:
       msg: Hello Indu
   - name: install nginx
     ansible.builtin.package: