- name: install nginx server
  hosts: webservers
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.debug:
       msg: Hello Indu
   - name: install nginx
     state: present 
     ansible.builtin.package: