- name: uninstall nginx
  hosts: webservers
  become: yes
  tasks:
   - name: disable nginx
     ansible.builtin.package:
       name: nginx
       state: absent


   - name: hello nresh
     ansible.builtin.debug:
       msg: hello indu papa