- name: uninstall nginx
  hosts: webservers
  become: yes
  tasks:
   - name: disable nginx
     ansible.builtin.package:
       name: nginx
       state: absent


   - name: hello nresh
     ansible.builtin.debug:
       msg: hello indu papa

   - name: copy file
     ansible.builtin.copy:
       source: /tmp/01.naresh.txt
       destination: /opt/01.naresh.txt