- name: uninstall nginx
  hosts: webservers
  become: yes
  tasks:
   - name: disable nginx
     ansible.builtin.service:
       name: nginx
       disabled: yes
   - name: hello nresh
     ansible.builtin.debug:
       msg: hello indu papa