- name: variables
  hosts: webservers
  become: yes
  vars:
    NAME: Naresh
    village: Ramapuram
  tasks:
   - name: print the variables from task level
     ansible.builtin.debug:
       msg: Hello {{ NAME }} I am from {{ village }}
   - name: print the variables from task level
     vars:
       NAME: NARESH
       village: RAMAPURAM
     ansible.builtin.debug:
        msg: Hello {{ NAME }} I am from {{ village }}