- name: variables
  hosts: webservers
  become: yes
  vars:
    NAME: Naresh
    village: Ramapuram
  tasks:
   - name: print the variables from play level
     ansible.builtin.debug:
       msg: Hello {{ NAME }} I am from {{ village }}
   - name: print the variables from task level
     vars:
       NAME: NARESH
       village: RAMAPURAM
     ansible.builtin.debug:
        msg: Hello {{ NAME }} I am from {{ village }}
   - name: Print the variables from file
     vars_files:
        - vars.yaml  # This is where your variables are defined
     tasks:
    - name: Print a greeting message
      ansible.builtin.debug:
        msg: "Hello {{ NAME }}, I am from {{ village }}"

    