- name: using variables to print some data
  hosts: web
  vars:
    NAME: devops
    COURSE: ansible
    DURATION: 10hrs
  tasks:
  - name: print some data
    ansible.builtin.debug:
      msg: I am learning {{NAME}} also {{COURSE}} and the duration is {{DURATION}} 
- name: print something
  hosts: web
  tasks:
  - name: print data
    ansible.builtin.debug:
      msg: we are learning {{NAME}} also {{COURSE}} and the duration is {{DURATION}}