- name: print variables from another file 
  hosts: web
  vars_prompt:
  - name: name
    prompt: please enter your name
    privte: false
  - name: village
    prompt: please enter your village name 
    private: false 
  # vars_files:
  # - vars.yaml
  tasks:
  - name: print data 
    ansible.builtin.debug:
      msg: My name is {{name}}, i am from {{village}}