- name: print the variables
  hosts: webservers
  vars_file:
   - vars.yaml
  tasks:
   - name: print the variable from file
     ansible.builtin.debug:
       msg: Hello {{ NAME }} I am from {{ village }}