- name: variables from prompt
  hosts: webservers
  vars_prompt:
  - name: naresh
    prompt: please enter the name
  - name: village
    prompt: where are you from?
  tasks:
  - name: prompt
    ansible.builtin.debug:
      msg: my name is {{naresh}} I am from {{village}}