- name: to know preferred args
  hosts: webservers
  vars:
    Name: naresh
    village: ramapuram
  tasks:
  - name: first one
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}
  - name: second one
    ansible.builtin.include_vars:
      file: vars.yaml
  - name: vars from file
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}