- name: to know preferred args
  hosts: webservers
  vars:
    Name: naresh
    village: ramapuram
  tasks:
    name: first one
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}