- name: to know preferred args
  hosts: webservers
  vars:
    Name: naresh
    village: ramapuram
  tasks:
  - name: first one declared variables
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}
  - name: second one from file
    ansible.builtin.include_vars:
      file: vars.yaml
  - name: vars from file
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}
    - name: print the variable from task level
       ansible.builtin.debug:
         msg: Hello {{ NAME }} I am from {{ village }}
      vars:
        NaMe: NN
        VLG: RPM