- name: to know preferred args
  hosts: webservers
  vars:
    Name: naresh
    village: ramapuram
  tasks:
  - name: first one declared variables
    ansible.builtin.debug:
      msg: Hello {{ Name }} I am from {{ village }}
  - name: second one from file
    ansible.builtin.include_vars:
      file: vars.yaml
  - name: file
    ansible.builtin.debug:
      msg: Hello {{ NAME }} I am from {{ village }}
  - name: vars from task level
    ansible.builtin.debug:
      msg: Hello {{ NAME }} I am from {{ village }}
    vars:
      NaMe: NN
      VLG: RPM
  - name: narsh
    prompt: who are you
    private: fasle
  - name: vllg
    prompt: where are you from?
    private: fasle
  - name: vars from prompt
    ansible.builtin.debug:
       msg: Hello {{ narsh }} I am from {{ vllg }}