- name: print information
  hosts: web
  tasks:
   - name: print some information
     ansible.builtin.debug:
        msg: This is task-01 from play-01 
   - name: print another some information
     ansible.builtin.debug:
        msg: This is task-02 from play-01
- name: print play-02 information
  hosts: web
  tasks: 
   - name: print play-02 information
     ansible.builtin.debug:
        msg: This is task-01 from play-02
   - name: print play-02 information
     ansible.builtin.debug:
        msg: This is task-02 from play-02
- name: print play-03 information
  hosts: web
  tasks:
   - name: print information from play-03
     ansible.builtin.debug:
        msg: This is task-01 from play-03
   - name: print information from play-03       
     ansible.builtin.debug:
        msg: This is task-02 from play-03
   - name: print information from play-03
     ansible.builtin.debug:            
        msg: This is task-03 from play-03

- name: install nginx
  hosts: web
  become: yes
  tasks:
   - name: install nginx
     ansible.builtin.package:
        name: nginx
        state: present
   - name: run nginx
     ansible.builtin.service:
        name: nginx
        state: started             
        enabled: yes