- name: print information
  hosts: web
  tasks:
   - name: print some information
     ansible.builtin.debug:
        msg: This is task-01 from play-01 
   - name: print another some information
     ansible.builtin.debug:
        msg: This is task-02 from play-01
- name: print play-02 information
  hosts: web
  tasks: 
   - name: print play-02 information
     ansible.builtin.debug:
      msg: This is task-01 from play-02
   - name: print play-02 information
     ansible.builtin.debug:
        msg: This is task-02 from play-02         
        