# Play level variables
# Task level variables
# variables from file
# vars from prompt
# variables from inventory
# variables from CLI
- name: find the first preference
  hosts: web
  vars:   
    naresh: Playlevel
  tasks:
  - name: playlevel variables
    ansible.builtin.debug:
      msg: I am from {{naresh}}
  - name: tasklevel variables
    vars:
      naresh: Tasklevel
    ansible.builtin.debug:
      msg: I am from {{naresh}}
- name: vars from another file
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: Variables from another file
    ansible.builtin.debug:
      msg: I am from {{naresh}}
- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: naresh
    prompt: please enter your naresh
    private: false      
  tasks:
  - name: variables from prompt
    ansible.builtin.debug:
      msg: I am from {{naresh}}  
- name: vars from inventory
  hosts: web
  tasks:
  - name: variables from inventory
    ansible.builtin.debug:
      msg: I am from {{naresh}}    
# - name: vars from cli
#   hosts: web
#   tasks: 
#   - name: variables from CLI
#     ansible.builtin.debug:
#       msg: I am from {{naresh}}      