- name: print devops nformation
  hosts: localhost
  connection: local
  vars:
  - course: DevOps with AWS
    duration: 120HRS
    topics:
      - Linux
      - Shell
      - Ansible
      - Terraform
      - Docker
      - k8s
    devops:
      ci: jenkins
      containers:
        - docker
        - k8s
      cmt: ansible
  tasks:
  - name: print given data
    ansible.builtin.debug:
      msg: I am learning {{course}}, duration is {{duration}}, and topics are {{topics}}, and live is {{live}}, explaination below {{devops}}.