# - name: print devops nformation
#   hosts: localhost
#   connection: local
#   vars:
#   - course: DevOps with AWS
#     duration: 120HRS
#     topics:
#       - Linux
#       - Shell
#       - Ansible
#       - Terraform
#       - Docker
#       - k8s
#     devops:
#       ci: jenkins
#       containers:
#         - docker
#         - k8s
#       cmt: ansible
#     live: true  
#   tasks:
#   - name: print given data
#     ansible.builtin.debug:
#       msg: I am learning {{course}}, duration is {{duration}}, and topics are {{topics}}, and live is {{live}}, explaination below {{devops}}.

- name: compare two numbers
  hosts: localhost
  connection: local
  vars:
  - naresh: 16
  tasks:
  - name: given number is less than 15
    ansible.builtin.debug:
      msg: given number {{naresh}} is less than 15
    when: naresh  < 15
  - name: given number is greater than 15
    ansible.builtin.debug:
      msg: given number {{naresh}} is greater than 15
    when: naresh > 15    