# - name: print four persons info
#   hosts: localhost
#   connection: local
#   become: true
#   tasks:
#   - name: print persons info
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: present
#     loop:
#     - nginx
#     - git
#     - ansible
#     - pgadmin4

# - name: uninstall nginx
#   hosts: localhost
#   connection: local
#   become: yes
#   tasks: 
#   - name: uninstall nginx
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: absent
#     loop:
#     - nginx

- name: uninstall nginx
  hosts: localhost
  connection: local
  become: yes
  tasks: 
  - name: check nginx is installed or not
    ansible.builtin.command: nginx -v
    register: naresh
    ignore_errors: true
  - name: print nginx info
    ansible.builtin.debug:
      msg: "nginx info: {{ naresh }}"
  - name: install nginx
    ansible.builtin.package:    
      name: nginx
      state: present
    when: naresh.rc != 0
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

# - name: check user data
#   hosts: localhost
#   connection: local
#   become: yes
#   tasks:
#   - name: check user info
#     ansible.builtin.command: id nareshnaidu
#     register: naresh
#     ignore_errors: yes
#   - name: print user info
#     ansible.builtin.debug:
#       msg: user info "{{ naresh }}"
#   - name: create a user
#     ansible.builtin.command: useradd nareshnaidu
#     when: naresh.rc != 0
  