- name: print four persons info
  hosts: localhost
  connection: local
  become: true
  tasks:
  - name: print persons info
    ansible.builtin.package:
      name: "{{ item }}"
      state: present
    loop:
    - nginx
    - git
    - ansible
    - pgadmin4