- name: create 3 instances
  hosts: localhost
  connection: local
  vars:
    sg_id: sg-07bc108ee968475d5
    image_id: ami-09c813fb71547fc4f
    vpc_id: subnet-07bf150db76d1a830
    zone_id: nareshtransportservices.online 
  tasks:
  - name: ansible to install boto3 and botocore
    ansible.builtin.pip:
      name:
      - boto3
      - botocore
      executable: pip3.9
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t2.micro
      security_group: "{{ sg_id }}"
      vpc_subnet_id: "{{ vpc_id }}"
      image_id: "{{ image_id}}"
    loop:
    - mysql
    - backend
    - frontend
    register: instance
  - name: print instances data
    ansible.builtin.debug:
      msg: "{{ instance }}"  

  - name: create r53 records
    amazon.aws.route53:
      state: present
      zone: "{{ zone_id }}"
      record: "{{ item.item.zone_id }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      wait: true
    loop: "{{ instance.results }}"  